### ISSUE TITLE
Provide metrics for jobs of protected items

### ISSUE THREAD

**Issue by avonwyss** [CometBackup/comet-prometheus-exporter#1]
These metrics could reflect all protected items which have been run. In order to make them useful for alerting with rules, I think that exposing (at least) the two last runs would be essential of each backup and restore jobs, along with a time offset since the run started and ended. Note: `{...}` is used as placeholder for the same labels as for the first item.
```
cometserver_protecteditem_job_running{protecteditem="x",user="y",device="z",type="files and folders",run="latest|2nd-latest",mode="backup|restore"}=0|1
cometserver_protecteditem_job_warnings{...}=1
cometserver_protecteditem_job_errors{...}=0
cometserver_protecteditem_job_file_count{...}=1234
cometserver_protecteditem_job_size_bytes{...}=1234
cometserver_protecteditem_job_transfer_bytes{...}=1234
cometserver_protecteditem_job_duration_seconds{...}=1234
cometserver_protecteditem_job_elapsed_seconds{...,since="start|end"}=1234
```

Usage for monitoring: files and their volume in bytes, durations, transferred bytes, aggregable by user, devices, types
Usage for alerting: failed (or newly failed) jobs, jobs which have not run for a long time, jobs which are long-running

**Comment by mason-cometbackup** [comment]
This would definitely be useful, and it would be very neat to see each of those attributes charted over time.

I'm a little wary that Prometheus will not perform well with this design. From https://prometheus.io/docs/practices/naming/ :

> every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

We're already exporting the unbounded set of user IDs in labels with the `device_is_online` metric (etc). This proposal would expand it significantly.

Is this the common practice? Do you know of any similar products that export metrics in this way?

It might be better to only produce aggregate metrics that are more targeted towards your final reports/dashboards,

**Comment by avonwyss** [comment]
In this context, "unbounded" does not mean an unbounded set of values per se, but ever-changing values. Think of a timestamp, a job GUID, session IDs, random numbers...

With regards to the specific Prometheus and Comet Backup instances, the users, protected items etc. are fairly static - pretty much like computer names. Widely used exporters, such as the node_exporter and wmi_exporter, include device and process names etc.

**Comment by mason-cometbackup** [comment]
Thanks for the explanation, that is reassuring.

I've added a set of `cometserver_lastbackup_` metrics that look at the last completed backup job. Comet Server is storing these efficiently under the `Statistics->LastBackupJob` keys on both Protected Items and Storage Vaults.

I haven't included that job's status, that's still outstanding.

I haven't included that job's "elapsed since start/end", I think you can determine this in PromQL using `time() - cometserver_lastjob_start_time` as per [[1]](https://prometheus.io/docs/practices/instrumentation/#timestamps-not-time-since).

---

For anything else (looking at two jobs, looking at currently running jobs, including restore jobs, ...) we need to query the Comet Server for a list of jobs by criteria, and then group/filter for interesting ones.

I'm not sure looking at the last two jobs (`current`/`previous`) is going to be sufficient -
- if there are three jobs running you will never see final statuses
- when new jobs start, the statistics would "jump" from the `current` to the `previous`, that will look strange when graphed

I think the most natural option would be to expose all the jobs with a `job_id` label, then you can do any extra filtering within Prometheus - but that's definitely violating the guideline about not using ever-changing label values.

**Comment by avonwyss** [comment]
Good catch about the "elapsed since", that's fine.

Regarding the last two jobs, what I am really after is the ability to detect changes of the result of jobs (e.g. detect new failure, still failing, fixed...), and my pragmatic approach was to gather the metrics of the two last jobs. That being said, I think that having just the last job is sufficient for a start.

Regarding the `job_id`, since this is a guid which changes for every job I agree that this is not a good fit for a label value. If there was an increasing integer job number available this could be used as numeric counter value however, maybe a count (grouped by protected item) could make for a good substitute?
e.g.: `cometserver_lastjob_count{...}=123`

**Comment by mason-cometbackup** [comment]
> If there was an increasing integer job number available this could be used as numeric counter value however, maybe a count (grouped by protected item) could make for a good substitute?
e.g.: cometserver_lastjob_count{...}=123

Unfortunately not, no such counter is available. It's also not possible to produce such a count on-demand since the Comet Server might have pruned old historic information.

But, the last job's start time (in UNIX epoch format) is probably a good replacement. Checking for changes in this value (e.g. with `rate()` or `irate()` or `changes()`) indicates a new job.

> what I am really after is the ability to detect changes of the result of jobs (e.g. detect new failure, still failing, fixed...)

I've now added the last job's status in 0daa56386b4efbdf0b232f6c53edae20ce3ffa31. It should be possible for Prometheus to detect changes to the `cometserver_lastjob_status{status="success"}` value.

I've used an "enum" style metric, without defining zeroes for other possible job states, to minimise how much excess data is generated and stored. But it might be more difficult to query. For instance see [[1]](https://stackoverflow.com/questions/43875918/prometheus-alert-on-change-in-value).

**Comment by avonwyss** [comment]
Thanks for adding the new metrics! Could you also add additional labels to the protected items in order to make them more versatile:

- protected item name
- device name and identifier
- protected item type (e,g, "files and folders" etc.)

Since these labels are logically related, this will (unless some item is renamed) not generate any more time series than with the current id label. It would however allow to group items by device and/or types and they would display a meaningful name when making a graph.

> Checking for changes in this value (e.g. with `rate()` or `irate()` or `changes()`) indicates a new job.

The `changes()` function on the timestamp should work in principe, I'll play around.

> `cometserver_lastbackup_status` ... I've used an "enum" style metric, without defining zeroes for other possible job states

Please do include the zeroes, or don't use an enum-style label. One can always filter those out via scrape drop relabeling config on the Prometheus side if one wants to reduce the number of metrics.

That being said, knowing the number of errors and warnings and whether the job is still running would seem more efficient to me: it would imply the status but also enable things like finding jobs with most errors or similar. In terms of timeseries generated it would be identical or maybe even better (each enum label generates a time-series, so typically you have one more).

**Comment by mason-cometbackup** [comment]
> Could you also add additional labels to the protected items in order to make them more versatile [...] Since these labels are logically related, this will (unless some item is renamed) not generate any more time series than with the current id label.

OK. I agree it should not cause additional time series to be created, so I've added these `_name` labels to the latest v0.5.0 release.

It has increased the total data size produced. Perhaps this could be optionally disabled by an extra environment variable parameter? But we can always revisit this if it ever turns out to be a problem in practice.

> Please do include the zeroes, or don't use an enum-style label.

OK, I've included the zero values in the latest v0.5.0 release. If you had written a PromQL statement that relied on the zero values not being present, it would need to be changed to support this update.

> That being said, knowing the number of errors and warnings and whether the job is still running would seem more efficient to me: it would imply the status

I agree it would be more efficient, but it would not fully imply the status - a Comet backup job status conveys some additional information about the exact type of error that is not reflected by a simple count. For example "failed because the quota exceeded" or "failed because it was cancelled" or "failed because it exceeded the timeout limit".

> but also enable things like finding jobs with most errors or similar

It's interesting, but the jobs with the most errors are not necessarily the most urgent to fix. For example, a database backup might only contain one file, and a single error line might mean the whole database is unrestorable. Compared with a large file selection backup, a dozen errors might occur with most of the backup still being restorable. The severity usually requires more context.

Although "Error count per file count" might be an interesting way of capturing this particular example.

**Comment by avonwyss** [comment]
> OK. I agree it should not cause additional time series to be created, so I've added these _name labels to the latest v0.5.0 release.

Unfortunately the device name is still not on the protected item, which makes it impossible to group backup items per device. Therefore please also add "device_id" and "device_name" as labels - this will still not add more time series (and the little additional data transferred when scraping is not an issue IMO, other exporters are way chattier).

**Comment by mason-cometbackup** [comment]
OK, I've added `device_id` and `device_name` as labels to the `lastbackup_*` metrics in commit 9207820154d35a0b775291588694bc05dba041ab in the v0.5.1 update.
